package com.eeo.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_course
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Course implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.course_id
     *
     * @mbg.generated
     */
    private Integer courseId;

    /**
     * Database Column Remarks:
     *   课程名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.course_name
     *
     * @mbg.generated
     */
    private String courseName;

    /**
     * Database Column Remarks:
     *   课程类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.course_type
     *
     * @mbg.generated
     */
    private String courseType;

    /**
     * Database Column Remarks:
     *   课程图像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.course_img
     *
     * @mbg.generated
     */
    private String courseImg;

    /**
     * Database Column Remarks:
     *   课程内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.course_coutent
     *
     * @mbg.generated
     */
    private String courseCoutent;

    /**
     * Database Column Remarks:
     *   课程创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.course_creattime
     *
     * @mbg.generated
     */
    private String courseCreattime;

    /**
     * Database Column Remarks:
     *   课程作者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.course_author
     *
     * @mbg.generated
     */
    private String courseAuthor;

    /**
     * Database Column Remarks:
     *   课程价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.course_price
     *
     * @mbg.generated
     */
    private String coursePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_course
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.course_id
     *
     * @return the value of tb_course.course_id
     *
     * @mbg.generated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.course_id
     *
     * @param courseId the value for tb_course.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.course_name
     *
     * @return the value of tb_course.course_name
     *
     * @mbg.generated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.course_name
     *
     * @param courseName the value for tb_course.course_name
     *
     * @mbg.generated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.course_type
     *
     * @return the value of tb_course.course_type
     *
     * @mbg.generated
     */
    public String getCourseType() {
        return courseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.course_type
     *
     * @param courseType the value for tb_course.course_type
     *
     * @mbg.generated
     */
    public void setCourseType(String courseType) {
        this.courseType = courseType == null ? null : courseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.course_img
     *
     * @return the value of tb_course.course_img
     *
     * @mbg.generated
     */
    public String getCourseImg() {
        return courseImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.course_img
     *
     * @param courseImg the value for tb_course.course_img
     *
     * @mbg.generated
     */
    public void setCourseImg(String courseImg) {
        this.courseImg = courseImg == null ? null : courseImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.course_coutent
     *
     * @return the value of tb_course.course_coutent
     *
     * @mbg.generated
     */
    public String getCourseCoutent() {
        return courseCoutent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.course_coutent
     *
     * @param courseCoutent the value for tb_course.course_coutent
     *
     * @mbg.generated
     */
    public void setCourseCoutent(String courseCoutent) {
        this.courseCoutent = courseCoutent == null ? null : courseCoutent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.course_creattime
     *
     * @return the value of tb_course.course_creattime
     *
     * @mbg.generated
     */
    public String getCourseCreattime() {
        return courseCreattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.course_creattime
     *
     * @param courseCreattime the value for tb_course.course_creattime
     *
     * @mbg.generated
     */
    public void setCourseCreattime(String courseCreattime) {
        this.courseCreattime = courseCreattime == null ? null : courseCreattime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.course_author
     *
     * @return the value of tb_course.course_author
     *
     * @mbg.generated
     */
    public String getCourseAuthor() {
        return courseAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.course_author
     *
     * @param courseAuthor the value for tb_course.course_author
     *
     * @mbg.generated
     */
    public void setCourseAuthor(String courseAuthor) {
        this.courseAuthor = courseAuthor == null ? null : courseAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.course_price
     *
     * @return the value of tb_course.course_price
     *
     * @mbg.generated
     */
    public String getCoursePrice() {
        return coursePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.course_price
     *
     * @param coursePrice the value for tb_course.course_price
     *
     * @mbg.generated
     */
    public void setCoursePrice(String coursePrice) {
        this.coursePrice = coursePrice == null ? null : coursePrice.trim();
    }
}